version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
  - dependency-name: xunit.runner.visualstudio
    versions:
    - 2.4.3
  - dependency-name: Microsoft.Extensions.Configuration.Json
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration.Binder
    versions:
    - 5.0.0
  - dependency-name: JetBrains.Annotations
    versions:
    - 2020.3.0
  - dependency-name: Microsoft.Extensions.Http
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Configuration
    versions:
    - 5.0.0
  - dependency-name: Serilog
    versions:
    - 2.10.0
